name: dev-deployment

on:
  push:
    branches:
      - main


jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 
        uses: actions/setup-python@v2
        with: 
          python-version: 3.12
      - name: Install Package
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Test
        run: pytest tests -v

  docker-build:
      runs-on: ubuntu-latest
      needs: deployment
      steps:
        - uses: actions/checkout@v4
        - name: Build Image
          uses: docker/build-push-action@v4
          with:
            context: .
            file: dockerfiles/dev.dockerfile
            push: false