name: prod-deployment

on:
  push:
    branches:
      - prod


jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.12
      - name: Install Package
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Test
        run: pytest tests -v
      

  docker-build:
      runs-on: ubuntu-latest
      needs: deployment
      steps:
        - uses: actions/checkout@v4
        - name: Tag Version
          id: tag_version
          uses: mathieudutour/github-tag-action@v6.1
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }} 
        - name: Docker Login
          uses: docker/login-action@v2
          with:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_TOKEN }} 
        - name: Build Image
          uses: docker/build-push-action@v4
          with:
            context: .
            file: Dockerfile
            push: true
            tags: saddamsatria/fastapi-boilerplate:${{steps.tag_version.outputs.new_tag}}
   